mindmap
  root((operator benefits))
    better support for stateful workloads<br/>e.g. operational tasks 
    extended reconciliation loop
      non-cluster resources<br/>e.g. S3 buckets
      in-cluster resources

    semantic extensibility
      elegant abstractions for domain objects<br/>‘classes’ and ‘methods’
