mindmap
  root((Operator benefits))
    create, configure and manage instances of complex stateful applications

    includes domain or application-specific knowlege
      automates common tasks

    builds upon controller concept

    extends Kubernetes API
