mindmap
  root((Operator))
    controller
      automate common tasks
      ::icon(fa fa-plus-circle)
      tap into control loop
      ::icon(fa fa-plus-circle)
    custom resource definition
      semantic extension
      ::icon(fa fa-plus-circle)
      requires administrator privileges
      ::icon(fa fa-minus-circle)
      upsets Helm
      ::icon(fa fa-minus-circle)
      version upgrades tricky
      ::icon(fa fa-minus-circle)

