mindmap
  root((Operator))
    controller
      automate common tasks
      ::icon(fa fa-plus-circle)
      integrate with control loop
      ::icon(fa fa-plus-circle)
    custom resource definition
      extend Kubernetes API
      ::icon(fa fa-plus-circle)
