---
config: {}
  # layout: elk
  # look: handDrawn
  # theme: neutral
---
flowchart TD
  style crd font-family:xkcd-script

  subgraph "Operator"
    controller["Controller"]
    Z((" "))
    crd["Custom resource definition"]
    etcd[("Cluster state")]
  end

  controller --> Z
  crd --> Z
  Z --> etcd
  Z -->|reconcile| Z
