mindmap
  root((Operator))
    creates, configures and manages instances of complex stateful applications

    includes domain or application-specific knowlege
      automates common tasks

    builds upon controller concept

    extends Kubernetes API
