---
config:
  theme: dark
---
quadrantChart
    x-axis Dev --> Ops
    y-axis Large blast radius --> Small blast radius
    quadrant-1 Preferred
    quadrant-2 Consider trade-offs
    quadrant-3 Avoid
    quadrant-4 Consider trade-offs
    Kyverno: [0.9, 0.9]
    Kubernetes Prometheus Stack: [0.75, 0.7]
    Flow operator: [0.1, 0.45]
    Strimzi: [0.75, 0.3]
    Elasticsearch: [0.8, 0.65]
    AWS: [0.9, 0.6]
    ACK: [0.70, 0.2]
