---

config:
  theme: default

---

timeline
    section Q3 2022
      July : Flow, Tap and Sink operators : Data Ops team tasked with creating a path to production
      August
      September
    section Q4 2022
      October :  Power to deploy operators withdrawn
      November
      December : Flows, Taps and Sinks on life support : Data Ops team switches focus to Kafka migrations
