---

config:
  theme: default

---

timeline
    section Q3 2022
      July : Flow, Tap and Sink operators : Data Ops team tasked with creating a path to production : Redundancies
      August : Health Graph Pipelines in progress
      September : Health Graph Pipelines in production
    section Q4 2022
      October :  More redundancies : Accidental deletion of Strimzi custom resource definitions : Power to deploy operators withdrawn
      November : Making the case for Health Graph Pipelines : Better Terraform support : More features
      December : Health Graph Pipelines abandoned : Flows, Taps and Sinks limp on futureless: Data Ops team switches focus to Kafka migrations
