---

config:
  theme: default

---

timeline
    section Q3 2022
      July : Flow, Tap and Sink operators : Data Ops team tasked with creating a path to production : Redundancies
      August : New platform in progress
      September : New platform in production
    section Q4 2022
      October :  More redundancies : Accidental deletion of Strimzi custom resource definitions : Power to deploy operators withdrawn
      November : Making the case for the new platform : Better Terraform support : More features
      December : New platform abandoned : Flows, Taps and Sinks on life support : Data Ops team switches focus to Kafka migrations
