---

config:
  theme: default

---

timeline
    section Q3 2022
      July
      August
      September
    section Q4 2022
      October :  Accidental deletion of Strimzi custom resource definitions
      November
      December
